### ISSUE TITLE
Use a diversion for /usr/sbin/sendmail instead of copying it around

### ISSUE THREAD

**Issue by dleidert** [rolehippie/nullmailer#19]
The role copies `/usr/sbin/sendmail` and then replaces it with a shell script. This change will be lost whenever the `nullmailer` package gets updated. Package updates overwrite all files belonging to the package. Thus, the script will be replaced by the original `sendmail` binary from the package. The sustainable variant is to create a diversion using `dpkg-divert`:

```
dpkg-divert --add --rename  --divert /usr/sbin/sendmail-bin /usr/sbin/sendmail
```

This will rename the binary as intended, but updates of the nullmailer package will not overwrite `/usr/sbin/sendmail`. Instead, they will update the diversion `/usr/sbin/sendmail-bin` and thus keep the binary up-to-date as well.

**Comment by tboerger** [comment]
Great input, that's something I would integrate.

**Comment by tboerger** [comment]
Thanks for the input, it's already part of the master branch and there will be an automated release on monday.
